apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-container
        image: docker.io/sandeep3119/test:v1
        ports:
        - containerPort: 80

